# Default configuration for 3D reconstruction

# Image processing
preprocessing:
  resize_max_dimension: 1000
  enhance_contrast: true

# Feature extraction
features:
  method: 'sift'  # 'sift', 'surf', or 'orb'
  max_features: 2000
  use_adaptive_threshold: false

# Feature matching
matching:
  ratio_threshold: 0.7
  geometric_verification: true
  min_matches: 20
  verification_method: 'fundamental'  # 'fundamental' or 'homography'
  ransac_threshold: 3.0

# Camera calibration
calibration:
  focal_length_factor: 1.2  # Focal length = factor * max(width, height)

# Structure from Motion
sfm:
  incremental: true
  refine_poses: true
  min_triangulation_angle_deg: 3.0
  reprojection_error_threshold: 4.0

# Visualization
visualization:
  point_size: 2
  camera_size: 6
  point_color_method: 'rgb'  # 'rgb', 'depth', or 'normal'